### ISSUE TITLE
Create schema for Gazeteer database

### ISSUE THREAD

**Issue by ChristinaLast** [Living-with-machines/lwmdb#3]
### Tasks
- [x] Meet with @mcollardanuy to discuss schema requirements
- [ ] Implement schema in `django.models` directory
- [ ] Migrate models so visible in local instance
