### ISSUE TITLE
:bug: Fix bugs with package installation

### ISSUE THREAD

**Issue by ChristinaLast** [Living-with-machines/lwmdb#4]
## Tasks
- [x] `Apache` install requirement added to documentation
- [ ] `psycopg2` install in poetry packaging
- [x] `postgresql` install and start command
- [ ] `python-dotenv` install in poetry packaging
