### ISSUE TITLE
Meta ticket for deploy issues

### ISSUE THREAD

**Issue by griff-rees** [Living-with-machines/lwmdb#87]
Meta ticket for deploy issues (prior to refactoring to separate issues):

- [ ] #89
- [ ] #88
- [x] #90
- [ ] #91
- [ ] Export `postgres` `docker` images for import speed
  - [ ] `x86` vs `m1` compatibility/speed
  - [ ] Manage version of `postgres` (14 to 15)
